# Generated by Django 4.2.3 on 2023-08-07 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_product_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=0)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.depot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.product')),
            ],
            options={
                'verbose_name': 'Depot Operation',
                'verbose_name_plural': 'Depot Operations',
            },
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('depot', 'product'), name='unique for stock'),
        ),
    ]
