# Generated by Django 4.2.3 on 2023-08-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_stock_stock_unique_for_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterField(
            model_name='balance',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
