# Generated by Django 4.2.3 on 2023-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_invoice_custom_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='custom_invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
