# Generated by Django 4.2.3 on 2023-08-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_alter_invoice_custom_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem', to='sale.invoice'),
        ),
    ]
