# Generated by Django 4.2.3 on 2023-08-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_alter_lineitem_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
