# Generated by Django 4.2.3 on 2023-08-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0013_rename_customer_id_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance', to='sale.invoice'),
        ),
    ]
